- name: create user
  tags: always
  ansible.builtin.user:
    name: simone
    groups: root

- name: Add sudoersfile for simone
  tags: always
  ansible.builtin.copy:
    src: sudoer_simone
    dest: /etc/sudoers.d/simone
    owner: root
    group: root
    mode: 0440

- name: Add ssh key for simone user
  tags: always
  ansible.builtin.authorized_key:
    user: simone
    key: "ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAILYYQH1gQVI2cCI5727EYNF0Mp3DGiDoHcf8QbsGoHuI tom@ubuntuws"
